### ISSUE TITLE
Archive Fork and re-sync

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/gatk-sv#23]
## Proposal

Archive the current state of `main` as a side branch (`main-archive`? - preservation of the commit hashes used to run previous workflows)
Sync the upstream `main` branch
Stop using the Docker builder workflow - resume stealing the images using [this script](https://github.com/populationgenomics/production-pipelines/blob/main/scripts/sync_gatk_sv_images.py)

### Reason

Our repo has become hard to sync with the upstream repo

We've carried out 2 types of change since then:
- a couple of functional tweaks (#6 #9) which were implemented early on to get workflows to succeed; If these are required for the tools to function we should upstream the changes. If they are not required (possibly already fixed upstream) we can dump them
- github workflow changes to build & push images to our artifactory (inc. a ton of trash commits in which I tried and failed to get this working)

### Issues

This repo contains the build instructions for some but not all of the docker images to use. We're diverging substantially from the upstream repo and we'd still need to copy some of [these images](https://github.com/broadinstitute/gatk-sv/blob/main/inputs/values/dockers.json) over into our infrastructure directly. IMO it's not worth the deviation to privately build some of them. Recent issues have included failed GATK-SV workflows because the latest WDL files required the latest GATK image, and our repo contained the WDL but not the build instructions.

An issue we should raise on the parent repo is that a lot of these images (e.g. `condense_counts_docker` and `gatk_docker`) have the names of individual developers in the paths - it would be good to understand the provenance of these images, so that we can better understand why there are multiple different GATK images, for example.

This repo contains 3 key elements: 
- WDL files
- Scripts
- Images

The workflows require all 3 of these to be completely in sync to work as intended. The simplest way of doing this is to sync the repo and images at the same time, we can do this each time a meaningful release is made upstream.

**Comment by vivbak** [comment]
From my perspective this proposal sounds fine.

**Comment by illusional** [comment]
As discussed, I've force pushed main of gatk-sv to e2e76a8. I've also added a [2023-08-23-archive tag](https://github.com/populationgenomics/gatk-sv/releases/tag/2023-08-23-archive), and applied branch protection rules to main-cpg-archive.
